[tool.poetry]
name = "ease"
version = "0.1.0"
description = ""
authors = ["itsklimov <itsklimov@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.104.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
